### ISSUE TITLE
remove the zk part in spartan_parallel

### ISSUE THREAD

**Issue by kunxian-xia** [scroll-tech/ceno-recursion#49]
The zk property in the old `spartan_parallel` which use DLOG-based field is achieved by using a homomorphic commitment. This kind of primitive does not exist in small-field like goldilocks and its extension. Therefore, we plan to remove the support of zk as the next step after merging #17.

**Comment by darth-cy** [comment]
https://github.com/scroll-tech/ceno-recursion/pull/53

**Comment by kunxian-xia** [comment]
This issue is resolved in #53.
